### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by whiver** [nikhilkalige/docblockr#118]
Hi!

I encounter a bug when I try to decorate a multiline comment. Here are the details:
1. Create a new Js document and type "/\* here's a comment */"
2. Let the cursor at the end of the line, hit Ctrl+Shift+P and choose "Docblockr: Decorate Multiline"

**Atom Version**: 1.0.2
**System**: Windows 7 Professional 64bits
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package, v0.7.3
### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At C:\Users\whooot\.atom\packages\docblockr\lib\docblockr-worker.js:411

TypeError: Cannot read property '0' of null
  at DocBlockrAtom.module.exports.DocBlockrAtom.decorate_multiline_command (C:\Users\whooot\.atom\packages\docblockr\lib\docblockr-worker.js:411:25)
  at atom-workspace.<anonymous> (C:\Users\whooot\.atom\packages\docblockr\lib\docblockr-worker.js:162:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\whooot\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:177:20)

```
### Commands

```
     -2:03.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:02.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:02.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:02.3.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -2:02.3.0 editor:indent (atom-text-editor.editor.is-focused)
 38x -1:06.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:34.6.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:32.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:19.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:16.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 docblockr:decorate-multiline (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "javascript-snippets",
      "save-session",
      "language-mustache",
      "feedback",
      "language-clojure",
      "language-go",
      "language-less",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-toml",
      "release-notes",
      "styleguide",
      "welcome",
      "line-count",
      "open-on-github",
      "linter-csslint",
      "auto-detect-indentation"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "audioBeep": false
  },
  "docblockr": {
    "auto_add_method_tag": true,
    "deep_indent": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.7.0
compare-files, v0.6.2
docblockr, v0.7.3
language-smarty, v1.2.0
linter, v1.2.4
linter-jshint, v1.1.4
linter-php, v1.0.2
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

![28-07-2015 09-29-15](https://cloud.githubusercontent.com/assets/394565/8925914/c7ccf274-350b-11e5-9a02-12939da0096b.png)

Thank you for you work!

**Comment by andrrrl** [comment]
I have same issue in: 
OS: XUbuntu 15.10 (Willy)
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
Docblockr: 0.7.3

File/line of error:
~/.atom/packages/docblockr/lib/docblockr-worker.js:370

**Comment by iamlikeme-x** [comment]
Same bug when its not a multiline comment:
```php
// This is a comment
```

This produces the error `Cannot read property 0 of null`, presumably to the method now being deprecated?

Full stack trace:

```
TypeError: Cannot read property '0' of null
    at DocBlockrAtom.module.exports.DocBlockrAtom.decorate_command (/home/oliver/.atom/packages/docblockr/lib/docblockr-worker.js:415:25)
    at atom-workspace.<anonymous> (/home/oliver/.atom/packages/docblockr/lib/docblockr-worker.js:162:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by iamlikeme-x** [comment]
Seems this has been fixed for single line comments, but not for multiline comments. Any news @nikhilkalige @MoritzKn

**Comment by skylize** [comment]
I've played around a bit and noted some odd behaviors around the decoration feature. It's working and usable if you just keep in mind the points below. The first one is kinda wtf!, but easy enough to deal with once you're aware of it.

1. Select your text from left to right, avoiding selection of empty lines after comment.
    * Selecting your comment text from right to left before decorating will throw error. 🙀
    * Selected spaces or empty lines preceding the open tag are ignored. 👍
    * Decorator will do nothing if: 
        * New line after closing tag is included in closing tag. 🤔
        * Any spaces are on last line after the closing tag (whether selected or not). 😣

2. Only try to use single line decorator for one line at a time, commented with `//` . 

3. Only try to use multi-line decorator for comments that fit the following:
    * first line is `/*` or `/**` with no text
    * last line is `*/` with no text
    * all other lines between begin with `*` lined up vertically with the opening/closing tags

**Comment by Jarvvski** [comment]
I'm still getting this issue when using decorate on a single line. Is there a fix I need to apply?

**Comment by MoritzKn** [comment]
Seems like this was fixed by @Fluvf and now released with 0.14.0
