### ISSUE TITLE
Not triggering on /** in javascript.

### ISSUE THREAD

**Issue by tregusti** [nikhilkalige/docblockr#120]
I just installed the docblockr plugin and restarted atom.

Creating a new file with this contents:

```js
function hello(name) {
  alert('Hello ' + name);
}
```

And then typing in `/**` on the line above the function statement only inserts the default snippet from atom.

```js
/**
 * [cursor]
 */
function hello(name) {
  alert('Hello ' + name);
}
```

My environment:

```
$ apm -v
atom 1.0.7
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.10
git 1.9.5.github.0
visual studio 2010
```

Should I somehow disable the default behaviour? It seems like the plugin is working somewhat at least since pressing enter inside of a jsdoc comment autmatically inserts the leading `*`.

**Comment by li-xinyang** [comment]
I do have the same issue here. I have to reinstall the package in order to make it functional again. However, once Atom restart **docblockr** will no longer work anymore.

**Comment by PymZoR** [comment]
Same issue here.

**Comment by cymruu** [comment]
According to this https://atom.io/packages/docblockr docblockr doesn't support javascript at the moment

**Comment by davepies** [comment]
+1

Atom@1.0.13
OSX@10.11

**Comment by cymruu** [comment]
Same issue, however guys you can switch syntax to c++ and then run dockblockr

**Comment by davepies** [comment]
Deactivated 'Simple mode' within the docblockr settings an voila!

**Comment by li-xinyang** [comment]
@davepies `Simple Mode` is deactivated by default.

**Comment by ethyde** [comment]
Same here : 

Atom : 1.019
Win : 8.1

**Comment by smithamax** [comment]
+1

**Comment by scholtzm** [comment]
+1. I usually disable/enable the package to fix this but it gets tedious.

**Comment by Mekitoji** [comment]
It'll trigger when pressing space after /**

/** [Tab] - simple comment
```javascript
/**
 * [cursor]
 */
function hello(name) {
  alert('Hello ' + name);
}
```
/** [Space][Tab] - execute docblockr 
```javascript
/** 
 * [hello description]
 * @method hello
 * @param  {[type]} name [description]
 * @return {[type]}      [description]
 */
function hello(name) {
  alert('Hello ' + name);
}
```
Enter and shift-enter keystroke work fine too:
/** [Enter]

**Comment by nikhilkalige** [comment]
I am currently busy with college projects.. So have not been able to do much work... I am not sure I will be able to work on it any time soon.... Any help would be appreciated. :(

**Comment by MoritzKn** [comment]
This was fixed with #189. In version 0.7.4 it shouldn't happen anymore.
@nikhilkalige can you please close this issue?

**Comment by dpkshrma** [comment]
Running Atom on ubuntu 14.04
Atom version: 1.10.2
Dockblockr version: 0.8.7

The problem still persists.

**Comment by MoritzKn** [comment]
@dpkshrma Your problem has very likely nothing to do with the issue described here. Please open a new issue and give a detailed description of your problem.

**Comment by dpkshrma** [comment]
@MoritzKn The issue I am facing seemed to be exactly the same as @tregusti described in the issue description. So, I didn't see a point to open a new one. Although, I am not sure what more information would be required to replicate it. Docblockr worked for the first time, but on Atom restart, it stopped triggering.

I am currently working with ES6 syntax which I believe was partially enabled by [this](https://github.com/malko/docblockr/commit/91f083b2d641fb61931aff4eabc4331c2dbb17a7) commit :
```
const testFunction = (testParam) => {
  return testParam;
};
```
Also, my environment details look like this:
```
$ apm -v
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.6
git 1.9.1
```

**Comment by MoritzKn** [comment]
@dpkshrma Your problem is probably occurring because one of these reasons:
- Another package adds a keybinding that overrides the event enter event. You can test this by using the [keybinding-resolver](https://github.com/atom/keybinding-resolver) with <kbd>cmd-.</kbd>
- You have docblockr configured to work in `Simple Mode`

I don't want to reopen this issue, because it described a problem that occurred due to new snippets in Atoms core packages and this problem is fixed.
If none of the described reasons applies or you need further help, *please open a new issue*.

**Comment by gerardg-dev** [comment]
It worked for me by typing `/**` and then the Tab key as opposed as my previous attempts by typing Enter or Space after having typed `/**`
