### ISSUE TITLE
Uncaught TypeError: this.event.target.getClosest is not a function

### ISSUE THREAD

**Issue by nibushibu** [nikhilkalige/docblockr#268]
[Enter steps to reproduce:]

1. Focus on commit message field
2. Type enter

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [docblockr](https://github.com/nikhilkalige/docblockr) package 0.10.0

### Stack Trace

Uncaught TypeError: this.event.target.getClosest is not a function

```
At /Users/nibushibu/.atom/packages/docblockr/lib/docblockr-worker.js:814

TypeError: this.event.target.getClosest is not a function
    at DocBlockrAtom.module.exports.DocBlockrAtom.get_relevant_editor (/packages/docblockr/lib/docblockr-worker.js:814:48)
    at DocBlockrAtom.module.exports.DocBlockrAtom.validate_request (/packages/docblockr/lib/docblockr-worker.js:203:25)
    at /packages/docblockr/lib/docblockr-worker.js:75:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:17.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:12 core:close (div.markdown-preview.native-key-bindings)
     -0:04.4.0 docblockr:parse-enter (input.hidden-input)
```

### Non-Core Packages

```
ascii-codes 0.3.3 
atom-alignment 0.13.0 
atom-beautify 0.29.24 
atom-dark-ui-slim 0.47.1 
atom-fix-path 0.1.0 
atom-html-preview 0.1.22 
atom-light-ui-slim 0.25.1 
atomic-chrome 0.3.0 
auto-encoding 0.7.0 
autocomplete-paths 1.0.5 
autocomplete-wordpress-hooks 0.2.2 
autoprefixer 3.7.0 
bezier-curve-editor 0.7.2 
busy-signal 1.4.1 
calc 0.4.0 
clipboard-plus 0.5.1 
color-picker 2.2.5 
cursor-history 0.10.1 
docblockr 0.10.0 
double-tag 0.8.0 
duotone-dark-syntax 2.1.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.6 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.8.1 
git-time-machine 1.5.9 
grammar-token-limit 0.1.1 
highlight-column 0.5.2 
highlight-line 0.12.0 
html-entities 0.4.0 
intentions 1.1.2 
japan-util 0.2.0 
japanese-zen-han-convert 0.5.0 
json-converter 0.2.4 
language-actionscript 0.2.0 
language-ejs 0.4.0 
language-postcss 1.3.1 
language-pug 0.0.21 
last-tab 0.1.6 
linter 2.1.4 
linter-coffeelint 1.2.1 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-scss-lint 3.1.0 
linter-ui-default 1.5.4 
local-history 4.2.0 
minimap 4.28.2 
minimap-autohider 1.4.0 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
monokai 0.24.0 
pigments 0.39.1 
project-manager 3.3.4 
regex-railroad-diagram 0.17.0 
regex-railroad-diagram-fork 0.17.6 
riot-tag 1.1.1 
set-syntax 0.3.2 
show-ideographic-space 1.0.2 
sort-lines 0.14.0 
space-tab 0.4.2 
split-diff 1.4.0 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.1 
tag 0.5.0 
todo 0.6.0 
todo-show 1.11.0 
toggle-quotes 1.0.1 
```

**Comment by MoritzKn** [comment]
Thanks for reporting! Fixed with `v0.10.1`.

**Comment by hpohlmeyer** [comment]
I just installed v0.10.1, which does not fix the issue for me.

**Comment by MoritzKn** [comment]
@hpohlmeyer seems like i messed it up. `v0.10.2``should work.
